[theme]
primaryColor = "lightblue"
backgroundColor = "#000000"
secondaryBackgroundColor = "#FFFFFF"
textColor = "darkgrey"
font = "Roboto"

body {
  background-color:#000000;
  color: white;
  font-family: "Roboto", sans-serif;
}

.secondary-background {
  background-color:#FFFFFF;
}

